### ISSUE TITLE
should cmake be 3.12 or higher?

### ISSUE THREAD

**Issue by avidan-efody** [Kuree/pysv#18]
add_compile_options doesn't seem to exist in cmake 3.4, only from 3.12 onwards

https://cmake.org/cmake/help/v3.12/command/add_compile_definitions.html

**Comment by Kuree** [comment]
You're right about this. I didn't pay much attention when I was writing the cmake file. I will fix it using the old `add_definitions`.

**Comment by Kuree** [comment]
Should be fixed in 832ed6c6240e4cdfd31553bb257868990eefbb90.
