### ISSUE TITLE
return type = list of int ?  also input as list of int ?

### ISSUE THREAD

**Issue by shobhitkapoor** [Kuree/pysv#20]
Hi

I am trying to use your library , can we use list on python and dynamic array from SV side ?
if yes then please guide how can I do it ?

Thanks
Shobhit

**Comment by IDjamKE** [comment]
Online reminder Open array function

**Comment by hmomkargit** [comment]
Hi,
I am looking forward for the same update. It would be great if we could pass an array from python or sv and vice-versa. 

Omkar

**Comment by FpgaJohn** [comment]
If anybody is still watching, you can make your own 'array' type and pass that in, populate it inside your Python code and use the results:
```
class MyList:
    @sv()
    def __init__(self):
        self._data = []

    @sv()
    def get_idx(self, idx):
        return self._data[idx]

    @sv
    def set_idx(self, idx, value):
        if len(self._data) > idx:
            self._data[idx] = value

    @sv()
    def append(self, value):
        self._data.append(value)

    @sv()
    def get_length(self):
        return len(self._data)

    def from_bytearray(self, in_byte_array):
        self._data = in_byte_array

@sv(out_list=MyList, return_type=DataType.Int)
def my_function(out_list: MyList) -> int:
    print(f'out_list.get_idx(100): {out_list.get_idx(0)}')
    out_list.set_idx(10, 100)
    ...
```

**Comment by Kuree** [comment]
Added as of [v0.3.0](https://github.com/Kuree/pysv/releases/tag/v0.3.0). It uses `memoryview` from `pybind`, which is a non-copy mutable view of the underlying array. As a result, returning an array allocated from the python is not supported (please change it to the function input arg).
